<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE reference PUBLIC "-//IXIA//DTD IXIA DITA Composite//EN" "../../system/dtd/ixia/IxiaDitabase.dtd">
<reference id="blackberry_user_identity_challenge" xml:lang="en-us">
    <title><apiname>challenge()</apiname></title>
    <shortdesc><i>Issue a request to challenge for identity</i></shortdesc>
    <refbody>
        <section>
            <title>Synopsis:</title>
            <pre scale="80">void blackberry.user.identity.challenge(idsProvider, type, flags, dataName, successCallback, failureCallback)</pre>
        </section>
        <section>
            <title>Arguments:</title>
            <dl>
                <dlentry>
                    <dt><varname>idsProvider</varname> {String}</dt>
                    <dd><p>The identity provider to send this request to.</p></dd>
                </dlentry>
                <dlentry>
                    <dt><varname>type</varname> {Number}</dt>
                    <dd><p>The type of data. Each provider may have a unique set of types that it is able to handle.  See the documentation for the provider for details on valid values.</p></dd>
                </dlentry>
                <dlentry>
                    <dt><varname>flags</varname> {Number}</dt>
                    <dd><p>Special flags for the operation. Each provider may have a unique set of flags that it supports.  See the documentation for the provider for details on valid values and their behaviour for this operation.</p></dd>
                </dlentry>
                <dlentry>
                    <dt><varname>successCallback</varname> {Function}</dt>
                    <dd><p>Function which is invoked upon successful operation of this method.</p></dd>
                </dlentry>
                <dlentry>
                    <dt><varname>failureCallback</varname> {Function}</dt>
                    <dd><p>Function which is invoked when this method fails. This callback contains an errorCode parameter to specify the failure condition.</p>
                        <dl>
                            <dlentry>
                                <dt><varname>result</varname> {JSON}</dt>
                                <dd><p>A JSON object containing details of the failure in the form below:
                                    <pre>{
                                        "result":"50004",
                                        "errorDescription":"The user could not be authenticated."
                                    }</pre></p></dd>
                            </dlentry>
                        </dl>
                    </dd>
                </dlentry>
                <dlentry>
                    <dt>Error Handling:</dt>
                    <dd><p>Requests that do not complete successfully will result in the failure callback being called with one of the following result codes:</p>
                    <p><ul>
                        <li>IDS_DEFAULT_ERROR: An internal error has occurred attempting to process the request.</li>
                        <li>IDS_NOT_ENOUGH_RESOURCES: There are not enough resources available to process the request.</li>
                        <li>IDS_ACCOUNT_LOCALLY_LOCKED_OUT: The account is currently locked, access is unavailable while locked.</li>
                        <li>IDS_USER_COULD_NOT_BE_AUTHENTICATED: The user could not be authenticated.</li>
                    </ul></p></dd>
                </dlentry>
            </dl>
        </section>
        <example>
            <title>Example:</title>
            <p><pre scale="80">
&lt;script type="text/javascript"&gt;
    function challengeSuccess(level) {
        alert("Challenge was successful: " + level);
    }

    function challengeFailure(result) {
        alert("Challenge failed: " + result.result + " details: " + result.failureInfo);
    }

    blackberry.user.identity.registerProvider("ids:rim:bbid");
    blackberry.user.identity.challenge("ids:rim:bbid", 0, 0, challengeSuccess, challengeFailure);
&lt;/script&gt;
            </pre></p>
        </example>
    </refbody>
</reference>
